### ISSUE TITLE
Install issues with 0.4.0

### ISSUE THREAD

**Issue by matmair** [invenhost/inventree-wled-locator#11]
Hello,
I have restarted invenhost, reinstalled the plugin, then it was initially deactivated:

![grafik](https://github.com/invenhost/inventree-wled-locator/assets/26651869/4d4f7bd9-3ec9-432f-b8c4-3b586653b02b)

After I activated it, the page reloaded and I can no longer access the settings:
![grafik](https://github.com/invenhost/inventree-wled-locator/assets/26651869/03651f77-e4ed-40ee-b9bf-b2ba7eea699b)

_Originally posted by @ThorstenStr in https://github.com/invenhost/inventree-wled-locator/issues/7#issuecomment-2199326837_

**Comment by matmair** [comment]
@ThorstenStr could you please activate debugging for your instance and post the error you get in the notifications after you have opened this page? You can open any page after calling the failing page and should see a notification for the error there (as a superuser)

**Comment by ThorstenStr** [comment]
Hello, I won't get to it until tomorrow. Until then, can you briefly explain to me what I have to do to activate debugging? I haven't been using inventree for that long.

**Comment by matmair** [comment]
We have instructions [here](https://docs.inventree.org/en/stable/start/intro/?h=debug#debug-mode), you need to set a config setting and restart the inventree services.

**Comment by ThorstenStr** [comment]
Hi,
here the Error
`<html><body>
<h1>NoReverseMatch
       at /settings/</h1>
  <pre class="exception_value">'inventree-wled-locator' is not a registered namespace inside 'plugin'</pre>
  
Request Method: | GET
-- | --
http://10.10.0.212/settings/
4.2.10
NoReverseMatch
'inventree-wled-locator' is not a registered namespace inside 'plugin'
/opt/inventree/env/lib/python3.9/site-packages/django/urls/base.py, line 77, in reverse
InvenTree.views.SettingsView
/opt/inventree/env/bin/python3.9
3.9.5
['/opt/inventree/InvenTree',  '/opt/inventree/env/bin',  '/opt/inventree',  '/usr/lib/python39.zip',  '/usr/lib/python3.9',  '/usr/lib/python3.9/lib-dynload',  '/opt/inventree/env/lib/python3.9/site-packages',  '/opt/inventree/env/lib/python3.9/site-packages/odf',  '/opt/inventree/env/lib/python3.9/site-packages/odf',  '/opt/inventree/env/lib/python3.9/site-packages/odf',  '/opt/inventree/env/lib/python3.9/site-packages/odf',  '/opt/inventree/env/lib/python3.9/site-packages/odf',  '/opt/inventree/env/lib/python3.9/site-packages/odf',  '/opt/inventree/env/lib/python3.9/site-packages/odf']
Fri, 05 Jul 2024 09:11:02 +0000


</body>
</html>`

`<html><body>
<h2>Error during template rendering</h2>
   <p>In template <code>/opt/inventree/InvenTree/templates/InvenTree/settings/mixins/settings_content.html</code>, error at line <strong>3</strong></p>
   <h3>'inventree-wled-locator' is not a registered namespace inside 'plugin'</h3>
   
1 | {% load plugin_extras %}
-- | --
 
{% plugin_settings_content plugin_key as plugin_settings_content %}
{% if plugin_settings_content %}
{{ plugin_settings_content\|safe }}
{% endif %}
 


</body>
</html>`

**Comment by ThorstenStr** [comment]
I also have request and traceback information, let me know if you need any of that

**Comment by ThorstenStr** [comment]
Hello,

do you have an update for me?

**Comment by philipp2310** [comment]
Same here.
Taking a look into it, don't have any clue about django or inventree, but should be something minor

**Comment by philipp2310** [comment]
quick fix: 

Invetree Settings (webUI) -> ENABLE_PLUGINS_URL -> True

A warning message in case this user mistake happens would be nice - but that is above my understanding how to implement

**Comment by DerTechnikerHD** [comment]
Same Issue:

Type:

NoReverseMatch

Path:

http://10.180.0.123/settings/

Info:

'inventree-wled-locator' is not a registered namespace inside 'plugin'

When:

23. August 2024 10:22

Data:

Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.9/site-packages/django/urls/base.py", line 71, in reverse
extra, resolver = resolver.namespace_dict[ns]

KeyError: 'inventree-wled-locator'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

File "/opt/inventree/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 220, in _get_response
response = response.render()

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/response.py", line 114, in render
self.content = self.rendered_content

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/response.py", line 92, in rendered_content
return template.render(context, self._request)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 175, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
return nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/defaulttags.py", line 238, in render
nodelist.append(node.render_annotated(context))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/defaulttags.py", line 321, in render
return nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 208, in render
return template.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 177, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 157, in render
return compiled_parent._render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 63, in render
result = block.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/loader_tags.py", line 208, in render
return template.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 177, in render
return self._render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 167, in _render
return self.nodelist.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in render
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 1005, in <listcomp>
return SafeString("".join([node.render_annotated(context) for node in self]))

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/base.py", line 966, in render_annotated
return self.render(context)

File "/opt/inventree/env/lib/python3.9/site-packages/django/template/library.py", line 237, in render
output = self.func(*resolved_args, **resolved_kwargs)

File "/opt/inventree/src/backend/InvenTree/plugin/templatetags/plugin_extras.py", line 38, in plugin_settings_content
return plg.get_settings_content(context.request)

File "/opt/inventree/env/lib/python3.9/site-packages/inventree_wled_locator/WledPlugin.py", line 183, in get_settings_content
<a class="btn btn-primary" href="{reverse('plugin:inventree-wled-locator:off')}">Turn off</a>

File "/opt/inventree/env/lib/python3.9/site-packages/django/urls/base.py", line 77, in reverse
raise NoReverseMatch(

django.urls.exceptions.NoReverseMatch: 'inventree-wled-locator' is not a registered namespace inside 'plugin'

**Comment by ThorstenStr** [comment]
Hi,
@matmair
is there any news here ? It would be great if the problem could be fixed.
many thanks 
Thorsten
